// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybbetihhhpoekxyzcsah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliYmV0aWhoaHBvZWt4eXpjc2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTg3MzMsImV4cCI6MjA1NzUzNDczM30.vG0mW6v-DJecyCz-T6H8Oar49INf3yj5iJeFTwFE-Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);